### ISSUE TITLE
unable to sync with Google Drive

### ISSUE THREAD

**Issue by warnat** [palant/pfp#129]
Access blocked: PfP: Pain-free Passwords’s request is invalid
ralf****@gmail.com
You can’t sign in because PfP: Pain-free Passwords sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of PfP: Pain-free Passwords, see [error details](https://accounts.google.com/).
Error 400: invalid_request

**Do I miss some preparations to use google drive?**

**Comment by palant** [comment]
Unfortunately, Google changed the way their API can be used, and our way of doing it is no longer working.

I no longer have time to maintain PfP and will be winding it down. This means in particular that this issue will no longer be fixed.

**Comment by Maryse47** [comment]
@palant does it mean you found better alternative and stopped using it?

**Comment by palant** [comment]
No, it means that I cannot give it the attention it needs. From the look of it, I’ll be going with KeypassXC now. It lacks some features I need, but adding these should be less effort than continuing to develop a password manager of my own.

**Comment by warnat** [comment]
I see. Thanks for passing by.

**Comment by Maryse47** [comment]
Ok, I'll stick with pfp which i consider superior to keepass and 99% feature complete.

**Comment by palant** [comment]
It also happens to need migrating to Manifest V3, otherwise it will stop working in Chrome fairly soon and in Firefox somewhat later.

**Comment by Maryse47** [comment]
That sucks. Would migrating to v3 be much complicated for pfp? Maybe you can spare some _last dance_ here :smile:

**Comment by palant** [comment]
I don’t know.

Interesting complication: manifest V3 support is only available as of Firefox 109. So it’s either not updating Firefox users or dropping compatibility with everything that isn’t the latest release.

**Comment by Maryse47** [comment]
I think not updating would be fine when you don't add anything new in the end.  At time ff drop old extension support esr would have support for v3.

**Comment by palant** [comment]
> That sucks. Would migrating to v3 be much complicated for pfp? Maybe you can spare some _last dance_ here

I’m on it. However, I’m starting to seriously wonder whether I’m doing anyone a favor with it. Most of the changes are pretty straightforward, but background page turning into a service worker is just…

* There no longer is a good way to maintain global state for the application. This requires significant changes to the logic, rather risky for an unmaintained extension.
* Password generation can no longer be delegated to a worker. Not sure how this will impact things, particularly when many passwords have to be generated in parallel on the All Passwords page.
* In addition to whatever bugs I might introduce, there are plenty of bugs around this service worker implementation in Chrome itself. I’m reading about show-stopper bugs fixed in Chrome 104 and 105, and I wonder whether things can be relied upon by now.

Altogether, the changes are definitely too extensive for the web version of the application. I would have to build extensions and the web version from different branches, the latter staying on Manifest V2 code – keeping them in sync would be yet again a considerable effort. At least the web version would be stable this way.

**Comment by Maryse47** [comment]
Thx, I'm grateful you spared some time for this.  The v3 situation involves mixed feelings.

I think the June 2023 deadline in chrome is actually dropped:
https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/uIu9HjLD3_c

It sounds like it's too early to start v3 work as browsers aren't ready yet. At same time I understand you don't want to extend activity here over time.

PS. It's hard to believe it was 7 years(!)

**Comment by Maryse47** [comment]
BTW: did you though about removing sync feature (gdrive/dropbox) from v2 (since it's broken anyway)? That would make extension totally offline and may cut some deps.

**Comment by palant** [comment]
The work is all done, see https://github.com/palant/pfp/tree/manifest-v3. Theoretically, we are all good. What’s missing are long-term experiences – whether the extension will continue working correctly, or whether the service worker will get stuck at some point. Question now is whether to release for Chrome from this branch or to do another MV2 release.

No, I’m not removing sync. Dropbox sync is still working correctly for me, so I’m not sure how many users are affected by issues here. remoteStorage sync is also working fine.

**Comment by Maryse47** [comment]
@palant now chromium [states](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline) they will be disabling v2 extensions around beginning of next year:

> Like any big launches, all these changes will begin in pre-stable channel builds of Chrome first – Chrome Beta, Dev, and Canary. The changes will be rolled out over the coming months to Chrome Stable, with the goal of completing the transition by the beginning of next year

so there is around half year left for v3 migration unless they got cold feet again. I think if v3 is supposed to be generally worse than v2 then you may wait with migrating as long as possible.
