### ISSUE TITLE
Non-website passwords

### ISSUE THREAD

**Issue by juliandoucette** [palant/pfp#41]
It would be nice to be able to use this tool for non-website passwords. It seems this can be done now by simply storing multiple unrelated passwords for one website. Can you make this easier? (Would you encourage me to take a stab at it?)

**Comment by palant** [comment]
So this is about passwords not associated with any particular website? @kzar already asked about notes not associated with any particular website, and [we agreed](https://github.com/palant/easypasswords/issues/22#issuecomment-238207308) that `notes.invalid` would be a good host name to store these on. Then again, if we want to store passwords there as well then maybe something more generic would be better - like `passwords.invalid` or `generic.invalid`.

The open question is still how a good UX for this would look like. On the one hand, we don't want to overload the user interface with options and buttons. On the other hand, it should be easy to get to those generic passwords. One option I see would be a "Show generic passwords" link on the same line as "Website name:" - right-aligned. This link should switch the current view to `generic.invalid`, the website name shouldn't actually appear in the text field however but only something like "none." Do you see any better options?

**Comment by kzar** [comment]
I think the best interface would be a search box. I really like that feature in LastPass, both the popup and the all passwords page could have a search box at the top which allows you to quickly find other sites and notes, that could find ones not associated with a domain too.

As for storing passwords not associated with domains, do you really need this if storing free-text notes without an associated domain works @juliandoucette? (I can't see how that would be too useful, since stuff like automated password-filling wouldn't work anyway.)
![lastpass-search](https://cloud.githubusercontent.com/assets/155710/19961953/47ac8284-a1ad-11e6-8fe9-e09046ef1028.png)

**Comment by palant** [comment]
> I think the best interface would be a search box.

That would be an advanced feature and a huge overkill here. LastPass is about the last application that I would take as a usability example, the route through the user interface is maximally obfuscated there.

**Comment by kzar** [comment]
Well I think it makes a lot of sense. The use case is something like "I want to see the secure note for my bank account to get the account number", I'd then click the LastPass icon and search for the name of my bank, then click the record I wanted to view.

How else could we make that as convenient?

**Comment by palant** [comment]
A search field can be discussed but definitely not in the context of this issue.

**Comment by Noitidart** [comment]
I don't know the right approach for this. But I frequently use this for non-webbrowser passwords. Like my Teamviewer and Skype passwords. I go visit skype.com and then get the  code then paste it back.

**Comment by Noitidart** [comment]
Maybe cross platform Electron app. I can help with this if you want to go that way.

**Comment by palant** [comment]
#52 has been resolved, I think we can continue with this one as well now. As established in #26, the site name for passwords not bound to a site is `pfp.invalid`. We should not expose it however, instead it should display as `(none)`. And it should be easiest if it shows up like that in the autocomplete list so that it can be selected there.

**Comment by gotgot1995** [comment]
> 
> 
> Maybe cross platform Electron app. I can help with this if you want to go that way.

Hi @Noitidart , I totally agree with you. I also use PfP all the time for non-website passwords. I tried placing the web-client into an electron project but it kinda failed. Maybe you could help me out if you know this stuff. 😄

For example, what would be great is being able to put the cross-platform packaged version onto a USB drive. Then I could have all my passwords, all the time, on any operating system 🙂
