### ISSUE TITLE
Chrome extension devbuild does not automatically refresh, requires master password rentry

### ISSUE THREAD

**Issue by kzar** [palant/pfp#48]
Each time I want to test a change I have to:

1. Type `gulp build-chrome`
2. Switch to Chrome, select the extensions tab, select to refresh the extension.
3. Click the Easy Password icon and re-enter my (long) master password.

It would be nice if I only had to perform step 1.

**Comment by palant** [comment]
Automating step 3 isn't going to work - you reloaded the extension, so the current state is gone. Even if we managed to save it across somehow (you didn't want to save the master password to disk, did you?), the version you pushed is slightly different - and how do you account for changes properly?

So only steps 1 and 2 can be automated - the former by watching the directory for changes (we already have a "watch" command but that one only works with Firefox), the latter by adding some marker for the extension to recognize that it changed and call `chrome.runtime.reload()`. Neither hasn't been implemented so far, simply because I didn't have such a pressing need for it.
