### ISSUE TITLE
Firefox - Focus input field when popup is opened

### ISSUE THREAD

**Issue by r-a-y** [palant/pfp#81]
In Chrome, clicking on the pfp toolbar button will open the "Enter master password" popup and the text field is automatically focused, making typing the password easy to do.

In Firefox, when clicking on the pfp toolbar button, the "Enter master password" popup opens, but the text field is not focused.  It requires an additional click on either the label or the text field in order to type the password.  Tested on Firefox 58.0.2 and latest version of pfp.

Can we focus the input field when the popup is opened, similar to Chrome?

**Comment by palant** [comment]
This seems to be [bug 1324255](https://bugzilla.mozilla.org/show_bug.cgi?id=1324255), resolved in Firefox 60 a few days ago. A work-around is being mentioned, namely delaying focusing. However, in case of PfP focusing already is delayed, due to the messaging happening there. So this work-around doesn't seem to be reliable, even if it works at all. This issue only seems to affect out-of-process WebExtensions, meaning `extensions.webextensions.remote` preference set to `true` - that's only the case on Windows by default right now.

**Comment by palant** [comment]
I verified that this bug affects us on Windows and that delayed focusing is ineffective. So there is nothing we can do about it, other than waiting for Firefox 60 to be released (scheduled for May 9). Closing as "invalid" because it's a Firefox bug, not ours.

**Comment by palant** [comment]
For reference, there is also [bug 1435687](https://bugzilla.mozilla.org/show_bug.cgi?id=1435687) which is not yet resolved. It is quite annoying because pressing Enter after autofilling won't work - a click is always required to submit the form.

**Comment by r-a-y** [comment]
Sorry, I should've mentioned I was using Windows!

Tested on Firefox Nightly and can confirm that the input field is focused now :+1:
