### ISSUE TITLE
Door hanger doesn't work in permanent private browsing mode

### ISSUE THREAD

**Issue by fmarier** [palant/pfp#92]
If you go into about:preferences#privacy and set:

* Firefox will `Never, remember history`

Then the icon that opens the PfP doorhanger doesn't work. The door hanger never actually opens.

**Comment by roguh** [comment]
I was unable to reproduce this bug on Firefox 61.0.2. The door hanger opens and seems to save its state even after I close tabs and windows. I could try an older version to try to reproduce this on 64-bit Linux.

**Comment by palant** [comment]
For me, the icon simply didn't appear. That's because you have to explicitly allow the extension in private windows. To do that, go to `about:addons` and select the extension. Under "Run in Private Windows" select "Allow." After that, everything seems to be working.

I now added an `incognito` setting to the extension's manifest but I don't think it will really change anything - this needs to be enabled manually in Firefox.
