### ISSUE TITLE
Allow setting default password length & character classes in settings

### ISSUE THREAD

**Issue by ghost** [palant/pfp#95]
I generally use longer than default passwords but exclude character classes that make passwords harder to type on mobile/foreign keyboards. I know the settings I use by heart and can easily set them but it is a bit annoying to do that every time I need a new password.
It would be cool if the extension settings allowed for changing the default.

**Comment by palant** [comment]
Let's see whether we can approach this issue from another angle. In general, it isn't advisable to change the default as it will make recreating passwords more complicated.

Having a 16 characters long password is perfectly reasonable even if you use lower-case letters only. It's not a human-chosen password, it can be considered random. So even if somebody can try a billion guesses per second, they will need on average 691,000 years (yes, hundreds of thousands of years) to crack your password. Attacking a random password of that length just isn't feasible, it's far more promising to try and guess your master password.

So the issue is mostly that you feel the necessity to type in passwords manually. Maybe you could expand on that. PfP are meant to be filled in automatically, with Copy&Paste being the less desirable fallback. I can understand that the mobile story is very suboptimal as long as #91 isn't solved. But maybe using the [web client](https://pfp.works/webclient/) along with sync functionality is better than typing in passwords? Besides, where are you typing them from?

**Comment by sknorr** [comment]
* The point about the password length = taken in general. However, I have the following two notes on that (and I recognize I am not a security expert in any sense):
  * In the vast majority of cases I auto-fill my passwords, so using a longer password creates zero extra work on my part (apart from the initial setup of course).
  * Afaict, I guess you are speaking about the current state of computing. (And assume that it develops more or less linearly..?)

* Manual typing:
Recent situation: My boss asks me about something on a Trello board they are not a member of. I have my phone but not my laptop with me. So, to show them properly, I need to log in to Trello on their computer. At that point, I can:
  1. Generate the password on my phone in Android Firefox and type manually
  2. Open the PfP page on their computer, fumble around a bit, and type my master password on their computer, with the possibility that it might be stored etc.

  In that case (and a number of similar cases), (i.) makes more sense to me. That is why I'd like to be able to type things out manually if necessary, and I would like to be able to do so even on an unfamiliar keyboard (e.g. a co-worker uses an QWERTY keyboard with a QWERTZ software layout).

**Comment by palant** [comment]
As of PfP 3.0, the password can be edited after being randomly generated. This should do as a solution here.
