### ISSUE TITLE
iOS - website not working there

### ISSUE THREAD

**Issue by Noitidart** [palant/pfp#97]
I was at a wedding last week and had only my iOS device, on iOS 10.3.2. I can't update to iOS, because i need this device on old version to test my iOS apps on for older os's. I needed login but safari browser, and other browser did not support the website, and extension couldn't be installed. 

Is there any solutions I can help you with here? I can help with a super quick and dirty mobile companion in react-native, so it can be done all offline. The JS engine there will have the same limitations of the browser, so we'll have to use native modules.

**Comment by palant** [comment]
It's likely something about their WebCrypto support. Unfortunately, Safari is the one browser that is impossible to test without owning specific hardware, and I have neither a Mac nor iOS.

**Comment by Noitidart** [comment]
I have a mac mini I can set it up for remote connect for you. I only use that for dev, and im not doing any mac dev right now. Would you like to try that?

**Comment by palant** [comment]
I just tried Epiphany which is also based on WebKit and the website works there.

Yes, I guess your Mac mini would be the best way to test things. I could take a look tomorrow in the morning. You can see my email address under https://palant.de/impressum/.

**Comment by Noitidart** [comment]
Thanks!! I'll set it up when I get home and email you :)

I have TeamViewer, is there something else you prefer?

**Comment by palant** [comment]
TeamViewer is good.

Just checked and Epiphany uses a WebKit build that matches Safari 12.0.1. Could it be that your Safari version is older?

**Comment by Noitidart** [comment]
Yeah I think its the Safari that comes with iOS 10.3.2 I'll check as soon as I get home.

**Comment by palant** [comment]
It seems that there is no easy way to install an older WebKit version. Given that the market share of iOS 10 appears to be [below 5% of all iOS devices](http://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide), this issues is best resolved as "won't fix" - we should require at least Safari 11.

I looked at the [Safari 11 release announcement](https://web.archive.org/web/20171114193322/https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html) and it seems that prefixing isn't the issue here. It's rather this point:

> * Includes new cryptographic algorithms like: AES-CFB, AES-GCM, ECDH, and PBKDF2.

Of course, without AES-GCM their WebCrypto support wasn't of any use to us. There isn't an easy workaround either.

**Comment by Noitidart** [comment]
Totally understand, thanks bro!
